// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTcPEC_xLHhv7_d5IQG0WKxA9iaGWB58g',
    appId: '1:1023856234975:web:65d4016e306e7fa58a746a',
    messagingSenderId: '1023856234975',
    projectId: 'jamapp-5206c',
    authDomain: 'jamapp-5206c.firebaseapp.com',
    storageBucket: 'jamapp-5206c.appspot.com',
    measurementId: 'G-TWXHGPZ7TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDplXzixElnqj5NY_PHLLIItDAFLEvbbc',
    appId: '1:1023856234975:android:6fd14f1c23eb68878a746a',
    messagingSenderId: '1023856234975',
    projectId: 'jamapp-5206c',
    storageBucket: 'jamapp-5206c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTAY__acf7yASeGcEwaBzUrLXk8CVoxys',
    appId: '1:1023856234975:ios:2b152fdceeeb6bb48a746a',
    messagingSenderId: '1023856234975',
    projectId: 'jamapp-5206c',
    storageBucket: 'jamapp-5206c.appspot.com',
    iosClientId: '1023856234975-hdmqfkr9di1nopq4odnpb2rg7i5ukj9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.jam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTAY__acf7yASeGcEwaBzUrLXk8CVoxys',
    appId: '1:1023856234975:ios:2b152fdceeeb6bb48a746a',
    messagingSenderId: '1023856234975',
    projectId: 'jamapp-5206c',
    storageBucket: 'jamapp-5206c.appspot.com',
    iosClientId: '1023856234975-hdmqfkr9di1nopq4odnpb2rg7i5ukj9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.jam',
  );
}
